<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>ObjectScript Macros</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#include</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dim</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#define</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def1arg</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ifdef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment-line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^///.*$</string>
					<key>name</key>
					<string>comment.line.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+//.*$</string>
					<key>name</key>
					<string>comment.line.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+;.*$</string>
					<key>name</key>
					<string>comment.line.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*#;.*$</string>
					<key>name</key>
					<string>comment.line.objectscript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>continue</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\s+\#\#(?i)(continue)\s*)</string>
					<key>name</key>
					<string>keyword.control.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>def1arg</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(\#\s*(?:(?i)def1arg))\s+((?&lt;id&gt;[a-zA-Z%][a-zA-Z0-9]*))(?:(\()(\s*\g&lt;id&gt;\s*)(\)))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.objectscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.objectscript</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;!\#\#continue)\n</string>
					<key>name</key>
					<string>meta.preprocessor.objectscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continue</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#digits</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.objectscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>define</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(\#\s*(?:(?i)define))\s+((?&lt;id&gt;[a-zA-Z%][a-zA-Z0-9]*))(?:(\()(\s*\g&lt;id&gt;\s*((,)\s*\g&lt;id&gt;\s*)*)(\)))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.objectscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.objectscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;!\#\#continue)\n</string>
					<key>name</key>
					<string>meta.preprocessor.objectscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continue</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.objectscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dim</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.objectscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.name</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.objectscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(\#\s*(?:(?i)dim))\s+((?&lt;id&gt;[a-zA-Z%][a-zA-Z0-9]*))(?:\s*(,)\s*((\g&lt;id&gt;)*))*(?:\s+((?i)As)(?:\s(\g&lt;id&gt;(?:\.\g&lt;id&gt;)*)))?</string>
					<key>name</key>
					<string>meta.preprocessor.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>ifdef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#\s*(?i)(?:if|ifdef|ifndef|elif|else|undef|endif))\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
					</dict>
					<key>contentname</key>
					<string>meta.preprocessor.objectscript</string>
					<key>end</key>
					<string>(?=(?:;|//|/\*))|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment-line</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(\#\s*(?:(?i)include))\s+([a-zA-Z%][a-zA-Z0-9]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.objectscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\$\$[a-zA-Z]([a-zA-Z0-9])*</string>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.objectscript_macros</string>
	<key>uuid</key>
	<string>B639220B-4146-47AF-A1D5-4C1B4D254A07</string>
</dict>
</plist>
