<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mac</string>
		<string>int</string>
	</array>
	<key>name</key>
	<string>ObjectScript Routine</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#elements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;=\s)\b(BREAK|B|SET|S|DO|D|KILL|K|GOTO|G|READ|R|WRITE|W|OPEN|O|USE|U|CLOSE|C|CONTINUE|FOR|F|HALT|H|HANG|JOB|J|MERGE|M|NEW|N|QUIT|Q|RETURN|RET|TSTART|TS|TCOMMIT|TC|TROLLBACK|TRO|THROW|VIEW|V|XECUTE|X|ZKILL|ZL|ZNSPACE|ZN|ZTRAP|ZWRITE|ZW|ZZDUMP|ZZWRITE)\b(?=( (?![=+-]|\&amp;|\|)|:|$))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;=\s)\b(LOCK|L)\b(?=( (?![=]|\&amp;|\|)|:|$))</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.multiline.objectscript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>comment.multiline.objectscript</string>
					<key>end</key>
					<string>(.*?\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.multiline.objectscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*#;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.macro.objectscript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//|;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.endline.objectscript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>##;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.endline.macro.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.objectscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.objectscript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>control-commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.objectscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;=\s)\b(IF|I|WHILE|FOR|F|TRY|CATCH|ELSE|E|ELSEIF)\b(?=( (?![=+-]|\&amp;|\|)|:|$))</string>
				</dict>
			</array>
		</dict>
		<key>elements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(##class)(\()([^)]+)(\))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[i|r]%[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[i|r]%"[^".]"</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.{1,2})(%?[a-zA-Z0-9]+)(?=\()</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.{1,2})(%?[a-zA-Z0-9]+)(?!\()</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.parameter.type.variable</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.{1,2}#)([a-zA-Z0-9]+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%?[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>variable.name.objectscrip</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\^%?[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>variable.name.global.objectscrip</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>entity.name.function.system.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\${2}[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>entity.name.function.local.objectscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\${3}[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>meta.preprocessor.objectscript</string>
				</dict>
			</array>
		</dict>
		<key>embedded</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embeddedSQL</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embeddedJS</string>
				</dict>
			</array>
		</dict>
		<key>embeddedJS</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&amp;js)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.special.js.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.js</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>embeddedSQL</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&amp;sql)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.special.sql.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.sql</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control-commands</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.dim.objectscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.as.objectscript</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(#dim)(\s)(%?[a-zA-Z0-9]+)(\s)(?:(As)(\s)(%?[a-zA-Z0-9.]+))?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.objectscript_macros</string>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.objectscript</string>
	<key>uuid</key>
	<string>86BFC911-CABE-4FD4-8B88-6DDE3AD6A7E6</string>
</dict>
</plist>
