<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cls</string>
	</array>
	<key>name</key>
	<string>ObjectScript Class</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>as</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(\bAs\b(?:\slist of)?)(\s+)(%?[a-z][0-9a-z]*(?:_[0-9a-z]+)*(?:\.[a-z][0-9a-z]*(?:_[0-9a-z]+)*)*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.objectscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#documentation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(^\bIndex\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(^(?=.{0,1})(?:|))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#index</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^(\bForeignKey\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\bParameter\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^(\bProjection\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\bProperty\b)(\s+)((?:%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)|(?:"[^".]+"))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^(\bRelationship\b)(\s+)((?:%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)|(?:"[^".]+"))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\b(?:Class|Client)?Method\b)(\s+)((?:%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)|(?:"[^".]+"))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(})$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#method</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\bQuery\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(})$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\bTrigger\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(})$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#trigger</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\XData\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>identifier.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(})$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#xdata</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^(\Storage\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>identifier.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(})$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storage</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.objectscript</string>
					<key>end</key>
					<string>^(?=})</string>
					<key>endCaptures</key>
					<dict/>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.objectscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>comment.objectscript_class</string>
					<key>end</key>
					<string>(.*?\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.objectscript_class</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(^\s*// .*)</string>
					<key>name</key>
					<string>comment.objectscript_class</string>
				</dict>
			</array>
		</dict>
		<key>documentation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^/// .*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>comment.block.documentation.objectscript_class</string>
					<key>end</key>
					<string>(^(?=.{0,1})(?:|))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>formal_spec</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.objectscript_class</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#as</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z][a-zA-Z0-9]*</string>
							<key>name</key>
							<string>variable.name.objectscrip</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.objectscript#constants</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>index</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\bOn\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*(?:\.[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)*)</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#documentation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>identifier.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^(\Include\b)(\s+)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*(?:\.[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^(\bClass\b)(\s)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*(?:\.[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.objectscript_class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(\bExtends\b)(\s)(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*(?:\.[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(\bExtends\b)(\s+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.objectscript_class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>whitespace.objectscript_class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.objectscript_class</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(%?[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*(?:\.[a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)*)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#class</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#formal_spec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter_value</string>
				</dict>
			</array>
		</dict>
		<key>parameter_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objectscript#constants</string>
				</dict>
			</array>
		</dict>
		<key>params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.objectscript_class</string>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>property</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
			</array>
		</dict>
		<key>query</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#formal_spec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql</string>
				</dict>
			</array>
		</dict>
		<key>sql</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.sql</string>
					<key>end</key>
					<string>^(?=})</string>
					<key>endCaptures</key>
					<dict/>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xml</string>
				</dict>
			</array>
		</dict>
		<key>trigger</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>xdata</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xdataStyle</string>
				</dict>
			</array>
		</dict>
		<key>xdataStyle</key>
		<dict>
			<key>begin</key>
			<string>^({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.objectscript_class</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>xml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.objectscript_class</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.xml</string>
					<key>end</key>
					<string>^(?=})</string>
					<key>endCaptures</key>
					<dict/>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.objectscript_class</string>
	<key>uuid</key>
	<string>C9CB138A-B316-4211-8D67-5C912B759673</string>
</dict>
</plist>
